### ISSUE TITLE
Cannot fetch manifest

### ISSUE THREAD

**Issue by ossamahmad** [NotGlop/docker-drag#32]
`$ python docker_pull.py bkimminich/juice-shop`
[-] Cannot fetch manifest for bkimminich/juice-shop [HTTP 404]
b'{"errors":[{"code":"MANIFEST_UNKNOWN","message":"OCI index found, but accept header does not support OCI indexes"}]}\n'

**Comment by almogtavor** [comment]
This is because they don't pass [all relevant `Accept` header values](https://stackoverflow.com/questions/69335984/problems-calling-dockers-v2-name-manifest-tag-api). This works: `Accept: application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json`

**Comment by NotGlop** [comment]
Issue related with OCI image manifest format, and followed in #34.
Thank you
